dist: xenial
language: python
cache: pip
sudo: false

install:
  - pip install -r requirements/dev.txt

#before_install:
#  - pip install -U pip setuptools virtualenvwrapper
#  - source $(which virtualenvwrapper.sh)
#  - wipeenv

script:
  - pip install django==$DJANGO
  - pytest --cov="async_fetcher"

after_success:
  - pip install codecov
  - codecov

after_failure:
  - dmesg | tail -n 100

matrix:
  fast_finish: true
  include:
    - { python: "3.6", env: DJANGO=1.11 }
    - { python: "3.6", env: DJANGO=2.0 }
    - { python: "3.6", env: DJANGO=2.1 }

    - { python: "3.7", env: DJANGO=2.0 }
    - { python: "3.7", env: DJANGO=2.1 }


notifications:
  email: false

