dist: xenial
language: python
cache: pip
sudo: false

install:
  - pip install -r requirements/dev.txt

#before_install:
#  - pip install -U pip setuptools virtualenvwrapper
#  - source $(which virtualenvwrapper.sh)
#  - wipeenv

script:
  - pip install django==$DJANGO aiohttp==$AIOHTTP
  - pytest --cov="async_fetcher"

after_success:
  - pip install codecov
  - codecov

after_failure:
  - dmesg | tail -n 100

matrix:
  fast_finish: true
  include:
    - { python: "3.6", env: [DJANGO=1.11, AIOHTTP=3.3.2] }
    - { python: "3.6", env: [DJANGO=2.0, AIOHTTP=3.4.4] }
    - { python: "3.6", env: [DJANGO=2.1, AIOHTTP=3.4.4] }

    - { python: "3.7", env: [DJANGO=2.0, AIOHTTP=3.4.4] }
    - { python: "3.7", env: [DJANGO=2.1, AIOHTTP=3.4.4] }


notifications:
  email: false

