dist: xenial
language: python
cache: pip
sudo: false

before_install:
  - pip install -U pip setuptools virtualenvwrapper
  - source $(which virtualenvwrapper.sh)
  - wipeenv

script:
  - pip3 install ./requirements/dev.txt --no-build-isolation
  - pip install django==$DJANGO
  - pytest

after_success:
  - pip install codecov
  - codecov -e TEST_SUITE

after_failure:
  - dmesg | tail -n 100

matrix:
  fast_finish: true
  include:
    - { python: "3.6", env: DJANGO=1.11 }
#    - { python: "3.6", env: DJANGO=2.0 }
#    - { python: "3.6", env: DJANGO=2.1 }
#    - { python: "3.6", env: DJANGO=master }
#
#    - { python: "3.7", env: DJANGO=2.0 }
#    - { python: "3.7", env: DJANGO=2.1 }
#    - { python: "3.7", env: DJANGO=master }


notifications:
  email: false

